In [201]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split
%matplotlib inline 

import warnings
warnings.filterwarnings("ignore")


# 1- 加载数据

In [202]:
H_price = load_boston()

In [203]:
H_price.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])

In [204]:
H_price.data.shape ##输出波士顿房价数据类型

(506, 13)

In [205]:
H_price.data

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [206]:
H_price.target.shape

(506,)

In [207]:
H_price.feature_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [208]:
X = H_price.data
y = H_price.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30, random_state=42)

In [224]:
X_train.shape[0]

354

In [210]:
X_test.shape

(152, 13)

In [225]:
y_train.shape[0]

354

In [212]:
y_test.shape

(152,)

# 2- 写算法（最小二乘法的线性回归，利用梯度下降法搜索损失函数的min值）


In [226]:
class LinearRegression_boston(object):

    def __init__(self):
        self.coef_ = None
        self.intercept_ = None
        self._beta = None

    def fit_gd(self, X_train, y_train, alpha=0.01, n_rounds=1e4):
        """根据训练数据集X_train, y, 使用梯度下降法训练Linear Regression模型"""
        assert X_train.shape[0] == y_train.shape[0], \
            "the size of X_train must be equal to the size of y_train"
        
        X_i = np.hstack([np.ones((len(X_train), 1)), X_train])
        initial_beta = np.zeros(X_i.shape[1])
        
        def Loss_Function(beta, X_i, y):
            """定义损失函数"""
            try:
                Loss_value = np.sum((y - X_i.dot(beta)) ** 2) / len(y)
                return Loss_value
            except:
                return float('inf')

        def Derivation_Beta (beta, X_i, y):
            """对beta求偏导"""
            Deri_resulat = np.empty(len(beta))
            Deri_resulat[0] = np.sum(X_i.dot(beta) - y)
            for i in range(1, len(beta)):
                Deri_resulat[i] = (X_i.dot(beta) - y).dot(X_i[:, i])
            return Deri_resulat * 2 / len(X_i)
            

        def Gradient_descent(X_i, y, initial_beta, alpha, n_rounds=1e4, epsilon=1e-8):
            """梯度下降过程"""
            beta = initial_beta
            cur_rounds = 0
            
            while cur_rounds < n_rounds:
                gradient = Derivation_Beta(beta, X_i, y)
                last_beta = beta
                beta = beta - alpha * gradient
                if (abs(Loss_Function (beta, X_i, y) - Loss_Function(last_beta, X_i, y)) < epsilon):
                    break

                cur_rounds += 1

            return beta

        
        
        self._beta = Gradient_descent(X_i, y, initial_beta, alpha, n_rounds)
        self.intercept_ = self._beta[0]
        self.coef_ = self._beta[1:]

        return self

    def __repr__(self):
        return "LinearRegression_boston()"


# 进行训练
因为不知道哪里出错，就直接用简单的数组进行训练了。

In [227]:
model = LinearRegression_boston()

In [232]:
X = np.array([[1,2],[3,4],[5,6]])
X

array([[1, 2],
       [3, 4],
       [5, 6]])

In [233]:
X.shape

(3, 2)

In [234]:
y = np.array([1,2,3])
y

array([1, 2, 3])

In [235]:
model.fit_gd(X, y)

LinearRegression_boston()

In [236]:
model.coef_

array([0.16771282, 0.33283537])

In [237]:
model.intercept_

0.16512255001552797

In [238]:
model._beta

array([0.16512255, 0.16771282, 0.33283537])